import re
import unittest
from pathlib import Path


APP_ROOT = Path(__file__).resolve().parents[1]


class ToddlerKeyboardAppTests(unittest.TestCase):
    def read(self, name):
        return (APP_ROOT / name).read_text(encoding="utf-8")

    def test_deployable_static_files_exist(self):
        for name in ("index.html", "styles.css", "app.js", "README.md"):
            with self.subTest(name=name):
                self.assertTrue((APP_ROOT / name).exists(), f"{name} should exist")

    def test_index_contains_dada_task_and_required_controls(self):
        html = self.read("index.html")

        self.assertIn("dada", html.lower())
        self.assertIn('class="word-stage"', html)
        self.assertIn("practice-strip", html)
        self.assertIn('id="target-word"', html)
        self.assertIn('id="typed-display"', html)
        self.assertIn('id="tap-prompt"', html)
        self.assertIn('id="language-select"', html)
        self.assertIn('class="target-word-input"', html)
        self.assertNotIn('id="word-input"', html)
        self.assertNotIn('id="use-word-button"', html)
        self.assertNotIn("Pick a word", html)
        self.assertNotIn("Make word", html)
        self.assertIn('id="fullscreen-button"', html)
        self.assertIn('id="caps-toggle"', html)
        self.assertIn('id="helper-truck"', html)
        self.assertIn('id="helper-message-bubble"', html)
        self.assertIn('id="help-type-button"', html)
        self.assertIn('class="truck-svg"', html)
        self.assertIn('class="truck-face"', html)
        self.assertIn('class="truck-smile"', html)
        self.assertIn('class="truck-frown"', html)
        self.assertIn('class="truck-mouth"', html)
        self.assertIn('class="truck-door"', html)
        self.assertIn('class="control-strip"', html)
        self.assertIn('class="color-panel"', html)
        self.assertIn('class="helper-copy"', html)
        self.assertNotIn('class="truck-tooth"', html)
        self.assertNotIn('id="emoji-feedback"', html)
        self.assertIn('id="word-presets"', html)
        self.assertIn('data-word="Dada"', html)
        self.assertIn('data-word="DADA"', html)
        self.assertIn('data-word="papa"', html)
        self.assertIn('data-word="Baby"', html)
        self.assertIn('data-word="cat"', html)
        self.assertIn('data-word="Dog"', html)
        self.assertIn('data-word="cashew"', html)
        self.assertIn('data-word="banana"', html)
        self.assertIn('data-word="cookie"', html)
        self.assertIn('aria-label="Choose red"', html)
        self.assertIn('aria-label="Choose orange"', html)
        self.assertIn('aria-label="Choose blue"', html)
        self.assertIn('aria-label="Choose green"', html)
        self.assertIn('aria-label="Choose yellow"', html)
        self.assertIn('aria-label="Choose purple"', html)
        self.assertIn('aria-label="Choose rainbow"', html)
        self.assertIn('data-key="d"', html)
        self.assertIn('data-key="a"', html)
        self.assertIn('id="sound-toggle"', html)

    def test_javascript_supports_typing_colors_sound_and_completion(self):
        js = self.read("app.js")

        self.assertRegex(js, r"let\s+targetWord\s*=\s*['\"]dada['\"]")
        self.assertIn("selectedColor", js)
        self.assertIn("wordInput", js)
        self.assertNotIn("useWordButton", js)
        self.assertIn("languageSelect", js)
        self.assertIn("languageWordSets", js)
        self.assertIn("activeLanguage", js)
        self.assertIn("renderPresetWords", js)
        self.assertIn("speakText", js)
        self.assertIn("SpeechSynthesisUtterance", js)
        self.assertIn("speechSynthesis", js)
        self.assertIn("speakLetter", js)
        self.assertIn("speakWord", js)
        self.assertIn("fullscreenButton", js)
        self.assertIn("setTargetWord", js)
        self.assertIn("wordInput.addEventListener(\"input\"", js)
        self.assertIn("syncWordSize", js)
        self.assertIn("normalizeWord", js)
        self.assertIn("rainbowColors", js)
        self.assertIn("colorMode", js)
        self.assertIn("colorForLetter", js)
        self.assertIn("requestFullscreen", js)
        self.assertIn("capsLockOn", js)
        self.assertIn("toggleCapsLock", js)
        self.assertIn("helperTruck", js)
        self.assertIn("helperMessageBubble", js)
        self.assertIn("helpTypeButton", js)
        self.assertIn("setHelperMood", js)
        self.assertIn("animateHelperTyping", js)
        self.assertNotIn("updateEmojiFeedback", js)
        self.assertNotIn("encouragingEmojis", js)
        self.assertNotIn("tryAgainEmojis", js)
        self.assertIn("handleLetter", js)
        self.assertIn("renderTypedLetters", js)
        self.assertIn("AudioContext", js)
        self.assertIn("checkCompletion", js)
        self.assertIn("keydown", js)
        self.assertIn("toLocaleLowerCase", js)
        self.assertNotIn("letter.toLowerCase(),", js)

    def test_css_uses_large_child_friendly_touch_targets(self):
        css = self.read("styles.css")

        self.assertIn(".word-stage", css)
        self.assertIn(".copy-card", css)
        self.assertIn(".word-presets-scroll", css)
        self.assertIn(".helper-truck", css)
        self.assertIn(".truck-svg", css)
        self.assertIn(".practice-strip", css)
        self.assertIn("grid-template-columns: 1fr 1fr", css)
        self.assertIn('"stage stage"', css)
        self.assertIn('"controls controls"', css)
        self.assertIn('"helper keyboard"', css)
        self.assertIn("grid-area: controls", css)
        self.assertIn("grid-area: helper", css)
        self.assertIn("repeat(9, minmax", css)
        self.assertIn("overflow-x: auto", css)
        self.assertIn("0.5fr) minmax(0, 1.5fr", css)
        self.assertIn(".helper-truck.good", css)
        self.assertIn(".helper-truck.try", css)
        self.assertIn(".helper-truck.helping", css)
        self.assertIn(".helper-truck.try .truck-frown", css)
        self.assertIn(".helper-truck.good .truck-smile", css)
        self.assertIn(".caps-toggle", css)
        self.assertIn("cursor: pointer", css)
        self.assertIn("overflow-x: auto", css)
        self.assertIn("cursor:", css)
        self.assertIn("height: 100dvh", css)
        self.assertIn("overflow: hidden", css)
        self.assertIn(".key-button", css)
        self.assertIn(".typed-display", css)
        self.assertIn("@media", css)
        self.assertRegex(css, re.compile(r"min-height:\s*(7[2-9]|[89][0-9])px"))


if __name__ == "__main__":
    unittest.main()
