import re
import unittest
from pathlib import Path


APP_ROOT = Path(__file__).resolve().parents[1]


class ToddlerKeyboardAppTests(unittest.TestCase):
    def read(self, name):
        return (APP_ROOT / name).read_text(encoding="utf-8")

    def test_deployable_static_files_exist(self):
        for name in ("index.html", "styles.css", "app.js", "README.md"):
            with self.subTest(name=name):
                self.assertTrue((APP_ROOT / name).exists(), f"{name} should exist")

    def test_index_contains_dada_task_and_required_controls(self):
        html = self.read("index.html")

        self.assertIn("dada", html.lower())
        self.assertIn('class="word-stage"', html)
        self.assertIn("practice-strip", html)
        self.assertIn('id="target-word"', html)
        self.assertIn('id="word-picture"', html)
        self.assertIn('class="word-picture"', html)
        self.assertIn('id="typed-display"', html)
        self.assertIn('id="tap-prompt"', html)
        self.assertIn('id="language-select"', html)
        self.assertIn('class="target-word-input"', html)
        self.assertNotIn('id="word-input"', html)
        self.assertNotIn('id="use-word-button"', html)
        self.assertNotIn("Pick a word", html)
        self.assertNotIn("Make word", html)
        self.assertNotIn('id="word-presets"', html)
        self.assertNotIn('class="word-editor"', html)
        self.assertNotIn('class="preset-button"', html)
        self.assertIn('id="fullscreen-button"', html)
        self.assertIn('id="caps-toggle"', html)
        self.assertIn('id="helper-computer"', html)
        self.assertIn('id="helper-message-bubble"', html)
        self.assertIn('id="help-type-button"', html)
        self.assertIn('class="computer-helper ready"', html)
        self.assertIn('class="computer-svg"', html)
        self.assertIn('class="computer-screen"', html)
        self.assertIn('class="computer-face"', html)
        self.assertIn('class="computer-smile"', html)
        self.assertIn('class="computer-frown"', html)
        self.assertIn('class="computer-keyboard"', html)
        self.assertIn('class="control-strip"', html)
        self.assertIn('class="color-panel"', html)
        self.assertIn('class="helper-copy"', html)
        self.assertNotIn('id="helper-truck"', html)
        self.assertNotIn('class="monster-truck', html)
        self.assertNotIn('class="monster-svg"', html)
        self.assertNotIn('class="truck-svg"', html)
        self.assertNotIn('class="truck-tooth"', html)
        self.assertNotIn('id="emoji-feedback"', html)
        self.assertNotIn('data-word=', html)
        self.assertIn('aria-label="Choose red"', html)
        self.assertIn('aria-label="Choose orange"', html)
        self.assertIn('aria-label="Choose blue"', html)
        self.assertIn('aria-label="Choose green"', html)
        self.assertIn('aria-label="Choose yellow"', html)
        self.assertIn('aria-label="Choose purple"', html)
        self.assertIn('aria-label="Choose rainbow"', html)
        self.assertIn('data-key="d"', html)
        self.assertIn('data-key="a"', html)
        self.assertIn('id="sound-toggle"', html)

    def test_javascript_supports_typing_colors_sound_and_completion(self):
        js = self.read("app.js")

        self.assertRegex(js, r"let\s+targetWord\s*=\s*['\"]dada['\"]")
        self.assertIn("wordBank", js)
        self.assertIn("practiceMode", js)
        self.assertIn('let practiceMode = "list"', js)
        self.assertIn("setManualTargetWord", js)
        self.assertIn("advanceToNextWord", js)
        self.assertIn("advanceTimer", js)
        self.assertIn("selectedColor", js)
        self.assertIn("wordInput", js)
        self.assertNotIn("useWordButton", js)
        self.assertIn("languageSelect", js)
        self.assertNotIn("languageWordSets", js)
        self.assertIn("activeLanguage", js)
        self.assertNotIn("renderPresetWords", js)
        self.assertIn("speakText", js)
        self.assertIn("wordPictures", js)
        self.assertIn("updateWordPicture", js)
        self.assertIn("wordPicture", js)
        self.assertIn("sessionStorageKey", js)
        self.assertIn("littleTypingColors.session.v1", js)
        self.assertIn("loadSavedSession", js)
        self.assertIn("saveSession", js)
        self.assertIn("localStorage.setItem", js)
        self.assertIn("localStorage.getItem", js)
        self.assertIn("loadSpeechVoices", js)
        self.assertIn("voiceForLanguage", js)
        self.assertIn("unlockSound", js)
        self.assertIn("soundClips", js)
        self.assertIn("preloadSoundClips", js)
        self.assertIn("playSoundClip", js)
        self.assertIn("playChime", js)
        self.assertIn("playSuccessSound", js)
        self.assertIn("playRetrySound", js)
        self.assertIn("context.resume", js)
        self.assertIn("speechSynthesis.resume", js)
        self.assertIn('"touchstart"', js)
        self.assertIn('"click"', js)
        self.assertIn("smoothVoiceDefaults", js)
        self.assertIn("SpeechSynthesisUtterance", js)
        self.assertIn("speechSynthesis", js)
        self.assertIn("speakLetter", js)
        self.assertIn("speakWord", js)
        self.assertIn("letter.toLocaleLowerCase(activeLanguage)", js)
        self.assertIn("speakLetter(rawLetter.toLocaleLowerCase(activeLanguage))", js)
        self.assertIn("waitForWordSpeech(targetWord).then(advanceToNextWord)", js)
        self.assertIn("utterance.onend = finish", js)
        self.assertIn("function rejectIncorrectLetter", js)
        self.assertIn("speakTapPrompt(expectedLetter)", js)
        self.assertIn("`tap ${letter.toLocaleLowerCase(activeLanguage)}`", js)
        self.assertIn("expectedNextLetter", js)
        self.assertIn("return false", js)
        self.assertIn("speakText(word.toLocaleLowerCase(activeLanguage)", js)
        self.assertNotIn("speakText(word.toLocaleUpperCase", js)
        self.assertIn("fullscreenButton", js)
        self.assertIn("setTargetWord", js)
        self.assertIn("wordInput.addEventListener(\"input\"", js)
        self.assertIn("syncWordSize", js)
        self.assertIn("normalizeWord", js)
        self.assertIn("rainbowColors", js)
        self.assertIn("colorMode", js)
        self.assertIn("colorForLetter", js)
        self.assertIn("requestFullscreen", js)
        self.assertIn("capsLockOn", js)
        self.assertIn("toggleCapsLock", js)
        self.assertIn("helperComputer", js)
        self.assertNotIn("helperTruck", js)
        self.assertIn("helperMessageBubble", js)
        self.assertIn("helpTypeButton", js)
        self.assertIn("setHelperMood", js)
        self.assertIn("animateHelperTyping", js)
        self.assertNotIn("updateEmojiFeedback", js)
        self.assertNotIn("encouragingEmojis", js)
        self.assertNotIn("tryAgainEmojis", js)
        self.assertIn("handleLetter", js)
        self.assertIn("renderTypedLetters", js)
        self.assertIn("AudioContext", js)
        self.assertIn("checkCompletion", js)
        self.assertIn("keydown", js)
        self.assertIn("moveFocusByDirection", js)
        self.assertIn("activateFocusedControl", js)
        self.assertIn("remoteControlKeys", js)
        self.assertIn('"ArrowUp"', js)
        self.assertIn('"ArrowDown"', js)
        self.assertIn('"ArrowLeft"', js)
        self.assertIn('"ArrowRight"', js)
        self.assertIn('"Enter"', js)
        self.assertIn("toLocaleLowerCase", js)
        self.assertNotIn("letter.toLowerCase(),", js)
        self.assertIn("formatVisibleWord", js)
        self.assertIn("updateTargetWordDisplay", js)
        self.assertIn("returnToListAfterManualWord", js)
        self.assertIn("8 + Math.random() * 36", js)
        self.assertIn("setTimeout(() => spark.remove(), 3200)", js)

    def test_javascript_has_100_child_friendly_words_per_language(self):
        js = self.read("app.js")
        languages = ("en-US", "es-ES", "fr-FR", "de-DE")

        for language in languages:
            with self.subTest(language=language):
                match = re.search(rf'"{language}":\s*\[(.*?)\]', js, re.S)
                self.assertIsNotNone(match, f"{language} should have a word list")
                words = re.findall(r'"([a-z]+)"', match.group(1))

                self.assertEqual(100, len(words), f"{language} should have 100 words")
                self.assertEqual(len(words), len(set(words)), f"{language} words should be unique")
                for word in words:
                    self.assertRegex(word, r"^[a-z]{1,8}$", f"{word} should fit the keyboard")

    def test_css_uses_large_child_friendly_touch_targets(self):
        css = self.read("styles.css")

        self.assertIn(".word-stage", css)
        self.assertIn(".copy-card", css)
        self.assertNotIn(".word-presets-scroll", css)
        self.assertNotIn(".word-editor", css)
        self.assertIn(".computer-helper", css)
        self.assertIn(".computer-svg", css)
        self.assertIn("@keyframes computer-dance", css)
        self.assertNotIn(".monster-truck", css)
        self.assertNotIn(".monster-svg", css)
        self.assertIn(".practice-strip", css)
        self.assertIn("grid-template-columns: 1fr 1fr", css)
        self.assertIn('"stage stage"', css)
        self.assertIn('"controls controls"', css)
        self.assertIn('"helper keyboard"', css)
        self.assertIn("grid-area: controls", css)
        self.assertIn("grid-area: helper", css)
        self.assertIn("repeat(9, minmax", css)
        self.assertIn("overflow-x: auto", css)
        self.assertIn("0.5fr) minmax(0, 1.5fr", css)
        self.assertIn(".computer-helper.good", css)
        self.assertIn(".computer-helper.try", css)
        self.assertIn(".computer-helper.helping", css)
        self.assertIn(".computer-helper.celebrating", css)
        self.assertIn(".computer-helper.celebrating .computer-screen", css)
        self.assertIn(".computer-disco-light", css)
        self.assertIn("@keyframes disco-screen", css)
        self.assertIn(".computer-helper.try .computer-frown", css)
        self.assertIn(".computer-helper.good .computer-smile", css)
        self.assertIn("@keyframes celebration-pop", css)
        self.assertIn("animation: celebration-pop", css)
        self.assertIn(".word-picture", css)
        self.assertIn("width: clamp(84px, 10vw, 136px)", css)
        self.assertIn("font-size: clamp(3.7rem, 7vw, 6.5rem)", css)
        self.assertIn("animation: computer-dance 430ms ease-in-out 10", css)
        self.assertIn("animation: celebration-pop 2400ms ease-out forwards", css)
        self.assertIn(".caps-toggle", css)
        self.assertIn("cursor: pointer", css)
        self.assertIn("overflow-x: auto", css)
        self.assertIn("cursor:", css)
        self.assertIn("height: 100dvh", css)
        self.assertIn("overflow: hidden", css)
        self.assertIn("--app-gap", css)
        self.assertIn("--key-height", css)
        self.assertIn("--color-size", css)
        self.assertIn("grid-template-rows: minmax(0, 0.9fr) minmax(0, 0.34fr) minmax(0, 1fr)", css)
        self.assertIn("@media (max-height: 760px)", css)
        self.assertIn("@media (max-height: 620px)", css)
        self.assertIn("height: min(100dvh, 100svh)", css)
        self.assertIn("max-height: 100dvh", css)
        self.assertIn(".key-button", css)
        self.assertIn(".typed-display", css)
        self.assertIn("@media", css)
        self.assertIn("min-height: var(--key-height)", css)
        self.assertIn("min-height: calc(var(--action-height) + 18px)", css)


if __name__ == "__main__":
    unittest.main()
